databases:
  - name: fiction
    databaseName: fiction
    user: fiction
    plan: free

services:
  - type: web
    name: fiction
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fiction
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
  - type: redis
    name: cache
    ipAllowList: [] # only allow internal connections
    plan: free
    maxmemoryPolicy: allkeys-lfu # optional (defaults to allkeys-lru). Rails recommends allkeys-lfu as a default.
